### ISSUE TITLE
Creat a Database

### ISSUE THREAD

**Issue by Oceanwalker10** [Oceanwalker10/Prioritize#11]
### Models

   | Property      | Type     | Description |
   | ------------- | -------- | ------------|
   | edTitle       | String   |Unigue name for each task |
   | edDescription | String   |Description of assignment, detailing how long it might take and what you need to do |
   | priorityNum   | Integer  | Number to tell how important task is  |
   | calendarDate  | Date     | Date at which the task needs to be completed|
   | id            | Number   | Primary Key(for if we do Google Calendar) |

**Comment by Izamakzi** [comment]
This is for if we do the stretch story of making the Google calendar.
